In [118]:
print("lets start")

lets start

In [119]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [120]:
df=pd.read_csv("../data/salesAnalysis.csv")

In [121]:
df.head()

,Order_ID,Customer_ID,Date,Age,Gender,City,Product_Category,Unit_Price,Quantity,Discount_Amount,Total_Amount,Payment_Method,Device_Type,Session_Duration_Minutes,Pages_Viewed,Is_Returning_Customer,Delivery_Time_Days,Customer_Rating
0,ORD_000001-1,CUST_00001,28-05-2023,40,Male,Ankara,Books,29.18,1,0.00,29.18,Digital Wallet,Mobile,14,9,True,13,4
1,ORD_000001-2,CUST_00001,12-10-2023,40,Male,Ankara,Home & Garden,644.40,1,138.05,506.35,Credit Card,Desktop,14,8,True,6,2
2,ORD_000001-3,CUST_00001,05-12-2023,40,Male,Ankara,Sports,332.82,5,0.00,1664.10,Credit Card,Mobile,15,10,True,9,4
3,ORD_000002-1,CUST_00002,11-05-2023,33,Male,Istanbul,Food,69.30,5,71.05,275.45,Digital Wallet,Desktop,16,13,True,4,4
4,ORD_000002-2,CUST_00002,16-06-2023,33,Male,Istanbul,Beauty,178.15,3,0.00,534.45,Credit Card,Mobile,14,7,True,6,4

In [122]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17049 entries, 0 to 17048
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Order_ID                  17049 non-null  object
 1   Customer_ID               17049 non-null  object
 2   Date                      17049 non-null  object
 3   Age                       17049 non-null  int64
 4   Gender                    17049 non-null  object
 5   City                      17049 non-null  object
 6   Product_Category          17049 non-null  object
 7    Unit_Price               17049 non-null  float64
 8   Quantity                  17049 non-null  int64
 9   Discount_Amount           17049 non-null  float64
 10  Total_Amount              17049 non-null  float64
 11  Payment_Method            17049 non-null  object
 12  Device_Type               17049 non-null  object
 13  Session_Duration_Minutes  17049 non-null  int64
 14  Pages_Viewed              17049 non-null  int64
 15  Is_Returning_Customer     17049 non-null  bool
 16  Delivery_Time_Days        17049 non-null  int64
 17  Customer_Rating           17049 non-null  int64
dtypes: bool(1), float64(3), int64(6), object(8)
memory usage: 2.2+ MB

In [123]:
df.describe()

,Age,Unit_Price,Quantity,Discount_Amount,Total_Amount,Session_Duration_Minutes,Pages_Viewed,Delivery_Time_Days,Customer_Rating
count,17049.000000,17049.000000,17049.000000,17049.000000,17049.000000,17049.000000,17049.000000,17049.000000,17049.000000
mean,34.945745,447.901689,3.011379,69.788135,1277.438711,14.535633,9.003109,6.503607,3.899408
std,11.046855,722.319705,1.417027,240.704662,2358.436375,2.925524,2.259954,3.488787,1.128803
min,18.000000,5.050000,1.000000,0.000000,6.210000,4.000000,1.000000,1.000000,1.000000
25%,26.000000,73.260000,2.000000,0.000000,172.970000,13.000000,7.000000,4.000000,3.000000
50%,35.000000,174.680000,3.000000,0.000000,455.850000,15.000000,9.000000,6.000000,4.000000
75%,42.000000,494.570000,4.000000,32.710000,1267.750000,17.000000,11.000000,8.000000,5.000000
max,75.000000,7900.010000,5.000000,6538.290000,37852.050000,26.000000,18.000000,25.000000,5.000000

In [124]:
df.duplicated().sum()
df.drop_duplicates(inplace=True)

In [125]:
df.columns = df.columns.str.strip()

In [126]:
for col in df.columns:
    print(f"{col} has {df[col].nunique()} unique values")

Order_ID has 17049 unique values
Customer_ID has 5000 unique values
Date has 450 unique values
Age has 57 unique values
Gender has 3 unique values
City has 10 unique values
Product_Category has 8 unique values
Unit_Price has 14711 unique values
Quantity has 5 unique values
Discount_Amount has 5526 unique values
Total_Amount has 15929 unique values
Payment_Method has 5 unique values
Device_Type has 3 unique values
Session_Duration_Minutes has 23 unique values
Pages_Viewed has 18 unique values
Is_Returning_Customer has 2 unique values
Delivery_Time_Days has 25 unique values
Customer_Rating has 5 unique values

In [127]:
df['Date'] = pd.to_datetime(df['Date'])

C:\Users\SOHAM\AppData\Local\Temp\ipykernel_92976\2394721818.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Date'] = pd.to_datetime(df['Date'])

In [128]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17049 entries, 0 to 17048
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Order_ID                  17049 non-null  object
 1   Customer_ID               17049 non-null  object
 2   Date                      17049 non-null  datetime64[ns]
 3   Age                       17049 non-null  int64
 4   Gender                    17049 non-null  object
 5   City                      17049 non-null  object
 6   Product_Category          17049 non-null  object
 7   Unit_Price                17049 non-null  float64
 8   Quantity                  17049 non-null  int64
 9   Discount_Amount           17049 non-null  float64
 10  Total_Amount              17049 non-null  float64
 11  Payment_Method            17049 non-null  object
 12  Device_Type               17049 non-null  object
 13  Session_Duration_Minutes  17049 non-null  int64
 14  Pages_Viewed              17049 non-null  int64
 15  Is_Returning_Customer     17049 non-null  bool
 16  Delivery_Time_Days        17049 non-null  int64
 17  Customer_Rating           17049 non-null  int64
dtypes: bool(1), datetime64[ns](1), float64(3), int64(6), object(7)
memory usage: 2.2+ MB

In [129]:
df['Delivery_Time_Days'].value_counts()

Delivery_Time_Days
4     2241
5     2231
6     2063
3     1985
7     1686
8     1354
2     1114
9     1095
10     800
11     733
12     524
13     302
1      233
14     213
15     157
17      73
16      72
18      56
20      35
19      28
22      13
21      12
23      11
24      10
25       8
Name: count, dtype: int64

In [130]:
within_7_days = (df["Delivery_Time_Days"] <= 7).sum()

above_7_days = (df["Delivery_Time_Days"] > 7).sum()

print("Delivered ≤ 7 days:", within_7_days)
print("Delivered > 7 days:", above_7_days)

Delivered ≤ 7 days: 11553
Delivered > 7 days: 5496

In [131]:
df["Total_Sales"] = df["Total_Amount"]

df["Avg_Item_Price"] = df["Total_Amount"] / df["Quantity"]

df["Discount_Percentage"] = np.where(
    df["Unit_Price"] * df["Quantity"] == 0,
    0,
    df["Discount_Amount"] / (df["Unit_Price"] * df["Quantity"])
)

In [132]:
df["Cost_Price"] = df["Unit_Price"] * 0.7
df["Profit"] = df["Total_Amount"] - df["Cost_Price"]
df["Profit_Margin"] = df["Profit"] / df["Total_Amount"]

In [133]:
df["Cart_Size"] = df["Quantity"]

In [134]:
df["Engagement_Score"] = df["Session_Duration_Minutes"] * df["Pages_Viewed"]

df["Pages_Per_Minute"] = np.where(
    df["Session_Duration_Minutes"] == 0,
    0,
    df["Pages_Viewed"] / df["Session_Duration_Minutes"]
)

In [135]:
EXPECTED_DELIVERY_DAYS = 7

df["Is_Delayed"] = (df["Delivery_Time_Days"] > EXPECTED_DELIVERY_DAYS).astype(int)

In [136]:
df["Rating_Category"] = pd.cut(
    df["Customer_Rating"],
    bins=[0, 2, 4, 5],
    labels=["Low", "Medium", "High"]
)

In [137]:
df.head()

,Order_ID,Customer_ID,Date,Age,Gender,City,Product_Category,Unit_Price,Quantity,Discount_Amount,...,Avg_Item_Price,Discount_Percentage,Cost_Price,Profit,Profit_Margin,Cart_Size,Engagement_Score,Pages_Per_Minute,Is_Delayed,Rating_Category
0,ORD_000001-1,CUST_00001,2023-05-28,40,Male,Ankara,Books,29.18,1,0.00,...,29.18,0.000000,20.426,8.754,0.300000,1,126,0.642857,1,Medium
1,ORD_000001-2,CUST_00001,2023-10-12,40,Male,Ankara,Home & Garden,644.40,1,138.05,...,506.35,0.214230,451.080,55.270,0.109154,1,112,0.571429,0,Low
2,ORD_000001-3,CUST_00001,2023-12-05,40,Male,Ankara,Sports,332.82,5,0.00,...,332.82,0.000000,232.974,1431.126,0.860000,5,150,0.666667,1,Medium
3,ORD_000002-1,CUST_00002,2023-05-11,33,Male,Istanbul,Food,69.30,5,71.05,...,55.09,0.205051,48.510,226.940,0.823888,5,208,0.812500,0,Medium
4,ORD_000002-2,CUST_00002,2023-06-16,33,Male,Istanbul,Beauty,178.15,3,0.00,...,178.15,0.000000,124.705,409.745,0.766667,3,98,0.500000,0,Medium

In [138]:

categorical_cols = df.select_dtypes(include='object').columns
numeric_cols= df.select_dtypes(include=['int64', 'float64']).columns

In [139]:
numeric_cols

Index(['Age', 'Unit_Price', 'Quantity', 'Discount_Amount', 'Total_Amount',
       'Session_Duration_Minutes', 'Pages_Viewed', 'Delivery_Time_Days',
       'Customer_Rating', 'Total_Sales', 'Avg_Item_Price',
       'Discount_Percentage', 'Cost_Price', 'Profit', 'Profit_Margin',
       'Cart_Size', 'Engagement_Score', 'Pages_Per_Minute'],
      dtype='object')

In [140]:
categorical_cols

Index(['Order_ID', 'Customer_ID', 'Gender', 'City', 'Product_Category',
       'Payment_Method', 'Device_Type'],
      dtype='object')

In [141]:
df.to_csv("../data/salesAnalysis_cleaned.csv", index=False)